### PR TITLE
Use Python 3.

### PR DESCRIPTION
**Pull request by djl**
## Description:
Headphones recently merged Python 3 support to the master branch, breaking the existing images.

Update the Dockerfiles to use baseimage-alpine image and update the services to use Python 3.

## Benefits of this PR and context:
Headphones actually works again 😄 

## How Has This Been Tested?
Built the container and ran it on my existing headphones data.

I have not been able to test anything other than amd64 but the others should work.

### CODE REVIEW

**Comment by thespad** [comment]
Please can you add a changelog entry in the readme-vars.yml

Also is git required at runtime? If not can you move it into the `build-dependencies` apk add.

**Comment by djl** [comment]
> Please can you add a changelog entry in the readme-vars.yml

Done.

> Also is git required at runtime? If not can you move it into the build-dependencies apk add.

Good catch. Fixed.

**Comment by thespad** [comment]
And after that it looks like it uses `git` for update checks so it does need to be there at runtime. Sorry.

Otherwise looks good and I'm happy to merge it.

**Comment by djl** [comment]
No worries. Reverted that change.

Do you want me to squash the changes to keep the history clean or is it fine as is?

**Comment by thespad** [comment]
It's fine I'll squash merge it.

**Pull request merged**
