### PR TITLE
Rebase to 3.18

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-headphones/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

### CODE REVIEW

**Comment by thespad** [comment]
Looks like it might not support Py 3.11

**Comment by aptalca** [comment]
Looks like upstream master needs to be updated for py3.11
https://github.com/rembo10/headphones/issues/3320#issuecomment-1585093931

**Comment by thespad** [comment]
I'm not sure realistically this is every going to be mergeable because it's been nearly a year since the last stable release with no sign there's going to be another one.

**Comment by aptalca** [comment]
I wonder if the develop branch builds/works. That branch only has two additional commits compared to the last stable and at least one of those was for py3.11 support.

On the other hand, upstream really doesn't seem to be getting much love so it may be time to sunset this regardless of the develop branch working.

**Pull request closed without merging**
